export const INCREMENT = 'INCREMENT';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const FILTER_SELECTED_ITEMS = 'FILTER_SELECTED_ITEMS';
export const REMOVE_FILTER_SELECTED_ITEMS = 'REMOVE_FILTER_SELECTED_ITEMS';
export const SET_LOCALE = 'SET_LOCALE';